export interface AgentParameter {
  id: string;
  label: string;
  type: 'text' | 'email' | 'time' | 'select' | 'number' | 'cron';
  placeholder?: string;
  defaultValue?: string;
  options?: { label: string; value: string }[];
  required?: boolean;
  description?: string;
}

export interface AgentTemplate {
  id: string;
  name: string;
  description: string;
  prompt: string;
  icon: string;
  category: string;
  color: string;
  parameters: AgentParameter[];
  businessAreas: string[]; // Tags for filtering by business area
}

export const agentTemplates: AgentTemplate[] = [
  {
    id: 'email-summarizer',
    name: 'Email Summarizer',
    description: 'Daily email summaries with priority highlights',
    prompt: 'Create an agent that reads my unread emails from {{email_address}} every day at {{schedule_time}}, categorizes them by urgency and importance using AI, and sends me a summary email with the top {{top_count}} emails I should respond to first.',
    icon: '📧',
    category: 'Productivity',
    color: 'from-blue-500 to-cyan-500',
    parameters: [
      {
        id: 'email_address',
        label: 'Email Address',
        type: 'email',
        placeholder: 'your@email.com',
        defaultValue: '',
        required: true,
        description: 'The email address to monitor',
      },
      {
        id: 'schedule_time',
        label: 'Schedule Time',
        type: 'time',
        defaultValue: '08:00',
        required: true,
        description: 'What time should the agent run daily?',
      },
      {
        id: 'top_count',
        label: 'Top Emails Count',
        type: 'number',
        defaultValue: '5',
        required: true,
        description: 'How many priority emails to highlight?',
      },
    ],
  },
  {
    id: 'social-monitor',
    name: 'Social Media Monitor',
    description: 'Track brand mentions and sentiment across platforms',
    prompt: 'Create an agent that monitors {{platform}} for mentions of "{{brand_name}}" every {{check_frequency}}, analyzes the sentiment of each mention using AI, and sends me a {{notification_channel}} notification if there are any {{alert_condition}} mentions that need immediate attention.',
    icon: '🐦',
    category: 'Marketing',
    color: 'from-purple-500 to-pink-500',
    parameters: [
      {
        id: 'platform',
        label: 'Social Platform',
        type: 'select',
        options: [
          { label: 'Twitter', value: 'Twitter' },
          { label: 'Instagram', value: 'Instagram' },
          { label: 'LinkedIn', value: 'LinkedIn' },
        ],
        defaultValue: 'Twitter',
        required: true,
      },
      {
        id: 'brand_name',
        label: 'Brand Name',
        type: 'text',
        placeholder: 'Your Brand',
        required: true,
        description: 'What brand or keywords to monitor?',
      },
      {
        id: 'check_frequency',
        label: 'Check Frequency',
        type: 'select',
        options: [
          { label: 'Every 15 minutes', value: '15 minutes' },
          { label: 'Every 30 minutes', value: '30 minutes' },
          { label: 'Every hour', value: 'hour' },
          { label: 'Every 4 hours', value: '4 hours' },
        ],
        defaultValue: '30 minutes',
        required: true,
      },
      {
        id: 'notification_channel',
        label: 'Notification Channel',
        type: 'select',
        options: [
          { label: 'Slack', value: 'Slack' },
          { label: 'Email', value: 'Email' },
          { label: 'SMS', value: 'SMS' },
        ],
        defaultValue: 'Slack',
        required: true,
      },
      {
        id: 'alert_condition',
        label: 'Alert On',
        type: 'select',
        options: [
          { label: 'Negative mentions', value: 'negative' },
          { label: 'All mentions', value: 'all' },
          { label: 'Urgent mentions only', value: 'urgent' },
        ],
        defaultValue: 'negative',
        required: true,
      },
    ],
  },
  {
    id: 'lead-qualifier',
    name: 'Lead Qualifier',
    description: 'Automatically score and qualify incoming leads',
    prompt: 'Create an agent that triggers when a new lead form is submitted via webhook to {{webhook_url}}, analyzes the lead data using AI to score it from 1-10 based on {{scoring_criteria}}, and automatically adds qualified leads (score > {{min_score}}) to {{crm_system}} with the AI reasoning.',
    icon: '🎯',
    category: 'Sales',
    color: 'from-green-500 to-emerald-500',
    parameters: [
      {
        id: 'webhook_url',
        label: 'Webhook URL',
        type: 'text',
        placeholder: 'https://your-domain.com/webhook',
        required: true,
        description: 'Where form submissions will be sent',
      },
      {
        id: 'scoring_criteria',
        label: 'Scoring Criteria',
        type: 'text',
        placeholder: 'company size, industry, budget',
        defaultValue: 'company size, industry, budget',
        required: true,
        description: 'What factors to consider when scoring?',
      },
      {
        id: 'min_score',
        label: 'Minimum Score',
        type: 'number',
        defaultValue: '7',
        required: true,
        description: 'Minimum score to qualify a lead (1-10)',
      },
      {
        id: 'crm_system',
        label: 'CRM System',
        type: 'select',
        options: [
          { label: 'HubSpot', value: 'HubSpot' },
          { label: 'Salesforce', value: 'Salesforce' },
          { label: 'Pipedrive', value: 'Pipedrive' },
        ],
        defaultValue: 'HubSpot',
        required: true,
      },
    ],
  },
  {
    id: 'content-curator',
    name: 'Content Curator',
    description: 'Weekly content summaries and insights',
    prompt: 'Create an agent that runs every {{schedule_day}} at {{schedule_time}}, collects all the articles I saved to {{content_source}} this week, generates a summary of the key insights and actionable takeaways using AI, and {{delivery_method}}.',
    icon: '📚',
    category: 'Research',
    color: 'from-orange-500 to-amber-500',
    parameters: [
      {
        id: 'schedule_day',
        label: 'Day of Week',
        type: 'select',
        options: [
          { label: 'Monday', value: 'Monday' },
          { label: 'Tuesday', value: 'Tuesday' },
          { label: 'Wednesday', value: 'Wednesday' },
          { label: 'Thursday', value: 'Thursday' },
          { label: 'Friday', value: 'Friday' },
        ],
        defaultValue: 'Friday',
        required: true,
      },
      {
        id: 'schedule_time',
        label: 'Time',
        type: 'time',
        defaultValue: '17:00',
        required: true,
      },
      {
        id: 'content_source',
        label: 'Content Source',
        type: 'select',
        options: [
          { label: 'Notion', value: 'Notion' },
          { label: 'Pocket', value: 'Pocket' },
          { label: 'Instapaper', value: 'Instapaper' },
        ],
        defaultValue: 'Notion',
        required: true,
      },
      {
        id: 'delivery_method',
        label: 'Delivery Method',
        type: 'select',
        options: [
          { label: 'Email me', value: 'emails it to me' },
          { label: 'Post to Slack', value: 'posts it to Slack' },
          { label: 'Save to Notion', value: 'saves it back to Notion' },
        ],
        defaultValue: 'emails it to me',
        required: true,
      },
    ],
  },
  {
    id: 'meeting-scheduler',
    name: 'Smart Meeting Scheduler',
    description: 'Intelligent meeting coordination and reminders',
    prompt: 'Create an agent that monitors my {{calendar_system}} calendar, sends personalized meeting reminders {{reminder_time}} before each meeting with agenda and participant info via {{reminder_channel}}, and suggests optimal meeting times based on my availability patterns.',
    icon: '📅',
    category: 'Productivity',
    color: 'from-indigo-500 to-purple-500',
    parameters: [
      {
        id: 'calendar_system',
        label: 'Calendar System',
        type: 'select',
        options: [
          { label: 'Google Calendar', value: 'Google Calendar' },
          { label: 'Outlook', value: 'Outlook' },
          { label: 'Apple Calendar', value: 'Apple Calendar' },
        ],
        defaultValue: 'Google Calendar',
        required: true,
      },
      {
        id: 'reminder_time',
        label: 'Reminder Time',
        type: 'select',
        options: [
          { label: '15 minutes', value: '15 minutes' },
          { label: '30 minutes', value: '30 minutes' },
          { label: '1 hour', value: '1 hour' },
          { label: '2 hours', value: '2 hours' },
        ],
        defaultValue: '1 hour',
        required: true,
      },
      {
        id: 'reminder_channel',
        label: 'Reminder Channel',
        type: 'select',
        options: [
          { label: 'Email', value: 'Email' },
          { label: 'Slack', value: 'Slack' },
          { label: 'SMS', value: 'SMS' },
        ],
        defaultValue: 'Email',
        required: true,
      },
    ],
  },
  {
    id: 'expense-tracker',
    name: 'Expense Tracker',
    description: 'Automated expense categorization and reporting',
    prompt: 'Create an agent that monitors my {{email_provider}} for receipt attachments, extracts the amount and vendor information, categorizes the expense using AI based on {{categories}}, and adds it to my {{tracking_system}} expense tracker with monthly summaries sent via {{summary_delivery}}.',
    icon: '💰',
    category: 'Finance',
    color: 'from-teal-500 to-cyan-500',
    parameters: [
      {
        id: 'email_provider',
        label: 'Email Provider',
        type: 'select',
        options: [
          { label: 'Gmail', value: 'Gmail' },
          { label: 'Outlook', value: 'Outlook' },
        ],
        defaultValue: 'Gmail',
        required: true,
      },
      {
        id: 'categories',
        label: 'Expense Categories',
        type: 'text',
        placeholder: 'Travel, Meals, Office Supplies, Software',
        defaultValue: 'Travel, Meals, Office Supplies, Software',
        required: true,
        description: 'Comma-separated list of categories',
      },
      {
        id: 'tracking_system',
        label: 'Tracking System',
        type: 'select',
        options: [
          { label: 'Airtable', value: 'Airtable' },
          { label: 'Google Sheets', value: 'Google Sheets' },
          { label: 'Notion', value: 'Notion' },
        ],
        defaultValue: 'Airtable',
        required: true,
      },
      {
        id: 'summary_delivery',
        label: 'Monthly Summary',
        type: 'select',
        options: [
          { label: 'Email', value: 'Email' },
          { label: 'Slack', value: 'Slack' },
        ],
        defaultValue: 'Email',
        required: true,
      },
    ],
  },
  {
    id: 'customer-support',
    name: 'Customer Support Assistant',
    description: 'Auto-respond to common customer inquiries',
    prompt: 'Create an agent that monitors my {{support_channel}} customer support inbox, identifies {{question_types}} using AI, drafts personalized responses in {{response_tone}} tone, and either sends them automatically for simple queries or flags complex ones for my review via {{review_channel}}.',
    icon: '💬',
    category: 'Support',
    color: 'from-rose-500 to-pink-500',
    parameters: [
      {
        id: 'support_channel',
        label: 'Support Channel',
        type: 'select',
        options: [
          { label: 'Email', value: 'Email' },
          { label: 'Zendesk', value: 'Zendesk' },
          { label: 'Intercom', value: 'Intercom' },
        ],
        defaultValue: 'Email',
        required: true,
      },
      {
        id: 'question_types',
        label: 'Question Types to Handle',
        type: 'text',
        placeholder: 'Pricing, Features, Technical Issues',
        defaultValue: 'common questions',
        required: true,
        description: 'What types of questions should it handle?',
      },
      {
        id: 'response_tone',
        label: 'Response Tone',
        type: 'select',
        options: [
          { label: 'Professional', value: 'professional' },
          { label: 'Friendly', value: 'friendly' },
          { label: 'Casual', value: 'casual' },
        ],
        defaultValue: 'friendly',
        required: true,
      },
      {
        id: 'review_channel',
        label: 'Review Channel',
        type: 'select',
        options: [
          { label: 'Email', value: 'Email' },
          { label: 'Slack', value: 'Slack' },
        ],
        defaultValue: 'Slack',
        required: true,
      },
    ],
  },
  {
    id: 'competitor-tracker',
    name: 'Competitor Tracker',
    description: 'Monitor competitor activities and updates',
    prompt: 'Create an agent that checks {{competitor_sources}} for new blog posts, product launches, or pricing changes from {{competitor_names}}, summarizes the key changes using AI focusing on {{focus_areas}}, and sends me a {{frequency}} digest every {{digest_day}} via {{delivery_channel}}.',
    icon: '🔍',
    category: 'Research',
    color: 'from-violet-500 to-purple-500',
    parameters: [
      {
        id: 'competitor_sources',
        label: 'Sources to Monitor',
        type: 'select',
        options: [
          { label: 'Websites', value: 'competitor websites' },
          { label: 'Social Media', value: 'social media' },
          { label: 'News Sites', value: 'news sites' },
        ],
        defaultValue: 'competitor websites',
        required: true,
      },
      {
        id: 'competitor_names',
        label: 'Competitor Names',
        type: 'text',
        placeholder: 'Company A, Company B, Company C',
        required: true,
        description: 'Comma-separated list of competitors',
      },
      {
        id: 'focus_areas',
        label: 'Focus Areas',
        type: 'text',
        placeholder: 'Pricing, Features, Marketing',
        defaultValue: 'pricing, features, marketing campaigns',
        required: true,
        description: 'What to pay attention to?',
      },
      {
        id: 'frequency',
        label: 'Digest Frequency',
        type: 'select',
        options: [
          { label: 'Daily', value: 'daily' },
          { label: 'Weekly', value: 'weekly' },
          { label: 'Bi-weekly', value: 'bi-weekly' },
        ],
        defaultValue: 'weekly',
        required: true,
      },
      {
        id: 'digest_day',
        label: 'Digest Day',
        type: 'select',
        options: [
          { label: 'Monday', value: 'Monday morning' },
          { label: 'Tuesday', value: 'Tuesday morning' },
          { label: 'Wednesday', value: 'Wednesday morning' },
          { label: 'Thursday', value: 'Thursday morning' },
          { label: 'Friday', value: 'Friday morning' },
        ],
        defaultValue: 'Monday morning',
        required: true,
      },
      {
        id: 'delivery_channel',
        label: 'Delivery Channel',
        type: 'select',
        options: [
          { label: 'Email', value: 'Email' },
          { label: 'Slack', value: 'Slack' },
        ],
        defaultValue: 'Email',
        required: true,
      },
    ],
  },
  {
    id: 'invoice-generator',
    name: 'Invoice Generator',
    description: 'Auto-generate and send professional invoices',
    prompt: 'Create an agent that triggers when I create a new entry in {{tracking_source}} with invoice details, generates a professional invoice using the data, saves it to {{storage_system}}, and emails it to the client using SendGrid from {{sender_email}} with a personalized message.',
    icon: '🧾',
    category: 'Finance',
    color: 'from-blue-500 to-indigo-500',
    parameters: [
      {
        id: 'tracking_source',
        label: 'Invoice Data Source',
        type: 'select',
        options: [
          { label: 'Google Sheets', value: 'Google Sheets' },
          { label: 'Airtable', value: 'Airtable' },
          { label: 'Notion', value: 'Notion' },
        ],
        defaultValue: 'Airtable',
        required: true,
      },
      {
        id: 'storage_system',
        label: 'Storage System',
        type: 'select',
        options: [
          { label: 'Google Drive', value: 'Google Drive' },
          { label: 'Notion', value: 'Notion' },
        ],
        defaultValue: 'Notion',
        required: true,
      },
      {
        id: 'sender_email',
        label: 'Sender Email',
        type: 'email',
        placeholder: 'invoices@company.com',
        required: true,
        description: 'Email address to send invoices from',
      },
    ],
  },
  {
    id: 'stripe-payment-tracker',
    name: 'Payment Success Tracker',
    description: 'Track successful payments and notify team',
    prompt: 'Create an agent that monitors Stripe for successful payments, extracts customer and payment details, sends a personalized thank-you email via SendGrid, notifies the {{team_channel}} Slack channel with the payment details, and logs it to {{record_system}} for record keeping.',
    icon: '💳',
    category: 'Finance',
    color: 'from-emerald-500 to-teal-500',
    parameters: [
      {
        id: 'team_channel',
        label: 'Slack Channel',
        type: 'text',
        placeholder: '#payments',
        defaultValue: '#payments',
        required: true,
        description: 'Slack channel to notify',
      },
      {
        id: 'record_system',
        label: 'Record System',
        type: 'select',
        options: [
          { label: 'Airtable', value: 'Airtable' },
          { label: 'Google Sheets', value: 'Google Sheets' },
          { label: 'HubSpot', value: 'HubSpot' },
        ],
        defaultValue: 'Airtable',
        required: true,
      },
    ],
  },
  {
    id: 'onboarding-automation',
    name: 'Customer Onboarding',
    description: 'Automated welcome sequence for new customers',
    prompt: 'Create an agent that triggers when a new customer signs up via webhook, sends a personalized welcome email via SendGrid from {{sender_email}}, creates a new contact in HubSpot with their details, schedules a follow-up task, and sends an onboarding checklist via {{notification_channel}}.',
    icon: '👋',
    category: 'Sales',
    color: 'from-pink-500 to-rose-500',
    parameters: [
      {
        id: 'sender_email',
        label: 'Sender Email',
        type: 'email',
        placeholder: 'hello@company.com',
        required: true,
        description: 'Email to send welcome messages from',
      },
      {
        id: 'notification_channel',
        label: 'Notification Channel',
        type: 'select',
        options: [
          { label: 'Slack', value: 'Slack' },
          { label: 'Email', value: 'Email' },
          { label: 'Discord', value: 'Discord' },
        ],
        defaultValue: 'Slack',
        required: true,
      },
    ],
  },
  {
    id: 'content-scheduler',
    name: 'Social Media Scheduler',
    description: 'Schedule and post social media content',
    prompt: 'Create an agent that reads content from my {{content_source}} content calendar every {{check_frequency}}, checks if any posts are scheduled for today, and automatically posts them to {{platforms}} at the specified times with the content and images.',
    icon: '📱',
    category: 'Marketing',
    color: 'from-cyan-500 to-blue-500',
    parameters: [
      {
        id: 'content_source',
        label: 'Content Calendar',
        type: 'select',
        options: [
          { label: 'Airtable', value: 'Airtable' },
          { label: 'Google Sheets', value: 'Google Sheets' },
          { label: 'Notion', value: 'Notion' },
        ],
        defaultValue: 'Airtable',
        required: true,
      },
      {
        id: 'check_frequency',
        label: 'Check Frequency',
        type: 'select',
        options: [
          { label: 'Every hour', value: 'hour' },
          { label: 'Every 2 hours', value: '2 hours' },
          { label: 'Every 4 hours', value: '4 hours' },
        ],
        defaultValue: 'hour',
        required: true,
      },
      {
        id: 'platforms',
        label: 'Platforms',
        type: 'text',
        placeholder: 'Twitter, LinkedIn',
        defaultValue: 'Twitter, LinkedIn',
        required: true,
        description: 'Comma-separated list of platforms',
      },
    ],
  },
];
