import { 
    Sparkles, 
    Zap, 
    Target, 
    TrendingUp, 
    Mail, 
    MessageSquare, 
    Image as ImageIcon, 
    FileText,
    BarChart3,
    Globe,
    Share2,
    Brain,
    Search,
    ShoppingCart,
    Video,
    Users,
    Star,
    Calendar,
    Megaphone,
    GitCompare,
    DollarSign,
    Briefcase,
    Lightbulb,
    FileCode,
    Headphones,
    Palette,
    PenTool,
    type LucideIcon
} from "lucide-react";

export type PowerUp = {
    id: string;
    name: string;
    description: string;
    icon: LucideIcon;
    category: string;
    isPopular?: boolean;
    isNew?: boolean;
    hasTools?: boolean; // Indicates power-up has interactive tools/builder inside
    gradient: string;
    businessValue: string;
    businessAreas: string[]; // Tags for filtering by helper/business area
};

export const BUSINESS_AREAS = [
    { id: 'marketing', label: 'Marketing' },
    { id: 'sales', label: 'Sales' },
    { id: 'finance', label: 'Finance' },
    { id: 'operations', label: 'Operations' },
    { id: 'customer', label: 'Customer Support' },
    { id: 'email', label: 'Email Marketing' },
    { id: 'tech', label: 'Technical/Dev' },
    { id: 'analytics', label: 'Analytics' },
    { id: 'ecommerce', label: 'E-commerce' },
    { id: 'content', label: 'Content Creation' },
    { id: 'social', label: 'Social Media' },
    { id: 'strategy', label: 'Strategy' },
] as const;

export const POWER_UPS: PowerUp[] = [
    // MARKETING Power-Ups (4)
    {
        id: "ai-ad-creator",
        name: "AI Static Ad Creator",
        description: "Generate high-converting static ads using advanced AI image models (Flux, Stable Diffusion, Midjourney-style). Perfect for Facebook, Instagram, LinkedIn, and display ads.",
        icon: ImageIcon,
        category: "Advertising",
        isNew: true,
        isPopular: true,
        hasTools: true, // Has ad builder tool
        gradient: "from-violet-500 to-purple-500",
        businessValue: "Create professional ads in minutes instead of hiring designers. Save $500-2000 per campaign.",
        businessAreas: ['marketing', 'social', 'ecommerce'],
    },
    {
        id: "seo-geo-optimizer",
        name: "SEO/GEO Optimizer Pro",
        description: "Complete SEO analysis with keyword research, meta tag generation, schema markup, local SEO, and GEO-targeted content optimization. Rank higher on Google.",
        icon: Search,
        category: "SEO & Growth",
        isPopular: true,
        gradient: "from-emerald-500 to-green-500",
        businessValue: "Increase organic traffic by 200-500%. Get found by customers searching for your products/services.",
        businessAreas: ['marketing', 'content', 'strategy'],
    },
    {
        id: "landing-page-builder",
        name: "AI Landing Page Builder",
        description: "Build high-converting landing pages with AI. Automatic A/B testing, CRO recommendations, and mobile optimization. Deploy in minutes.",
        icon: FileText,
        category: "Conversion",
        isNew: true,
        hasTools: true, // Has page builder tool
        gradient: "from-blue-500 to-cyan-500",
        businessValue: "Launch campaigns faster. Improve conversion rates by 25-40% with AI-optimized designs.",
        businessAreas: ['marketing', 'sales', 'ecommerce'],
    },
    {
        id: "ad-campaign-optimizer",
        name: "Ad Campaign Optimizer",
        description: "Optimize Facebook, Google, TikTok, and LinkedIn ads with AI. Automatic bid adjustments, audience refinement, and creative testing.",
        icon: Target,
        category: "Advertising",
        gradient: "from-rose-500 to-red-500",
        businessValue: "Reduce ad costs by 30-50%. Increase ROAS by 2-5x with AI-powered optimization.",
        businessAreas: ['marketing', 'analytics', 'strategy'],
    },

    // SALES Power-Ups (4)
    {
        id: "sales-funnel-builder",
        name: "Sales Funnel Builder",
        description: "Build complete sales funnels with order bumps, upsells, downsells, and thank you pages. Maximize revenue per customer.",
        icon: Zap,
        category: "Sales",
        hasTools: true, // Has funnel builder tool
        gradient: "from-red-500 to-orange-500",
        businessValue: "Increase average order value by 30-80%. Turn $50 customers into $150+ customers.",
        businessAreas: ['sales', 'marketing', 'ecommerce'],
    },
    {
        id: "lead-scoring-ai",
        name: "AI Lead Scoring & Qualification",
        description: "Automatically score and qualify leads based on behavior, demographics, and engagement. Prioritize hot leads for your sales team.",
        icon: TrendingUp,
        category: "Sales",
        isNew: true,
        gradient: "from-green-500 to-emerald-500",
        businessValue: "Focus on leads that convert. Increase close rates by 40-60% by prioritizing the right prospects.",
        businessAreas: ['sales', 'analytics', 'operations'],
    },
    {
        id: "proposal-generator",
        name: "Sales Proposal Generator",
        description: "Create professional sales proposals and quotes in minutes. Customizable templates, e-signatures, and tracking. Know when prospects open your proposal.",
        icon: FileText,
        category: "Sales",
        gradient: "from-blue-500 to-indigo-500",
        businessValue: "Close deals faster. Reduce proposal creation time from hours to minutes. Track engagement.",
        businessAreas: ['sales', 'operations'],
    },
    {
        id: "crm-automation",
        name: "CRM Automation Suite",
        description: "Automate data entry, follow-ups, task creation, and pipeline management. Sync with Salesforce, HubSpot, Pipedrive, and more.",
        icon: Briefcase,
        category: "Sales",
        isPopular: true,
        gradient: "from-purple-500 to-pink-500",
        businessValue: "Save 10+ hours/week on admin tasks. Never miss a follow-up. Keep your CRM pristine automatically.",
        businessAreas: ['sales', 'operations', 'customer'],
    },

    // FINANCE Power-Ups (4)
    {
        id: "invoice-generator-pro",
        name: "Invoice Generator Pro",
        description: "Create professional invoices, track payments, send reminders, and manage expenses. Multi-currency support and accounting software integration.",
        icon: DollarSign,
        category: "Finance",
        isPopular: true,
        gradient: "from-amber-500 to-yellow-500",
        businessValue: "Get paid faster. Reduce late payments by 50%. Automate your entire billing process.",
        businessAreas: ['finance', 'operations', 'ecommerce'],
    },
    {
        id: "financial-forecasting",
        name: "Financial Forecasting & Planning",
        description: "AI-powered financial projections, cash flow forecasting, budget planning, and scenario modeling. Make data-driven financial decisions.",
        icon: BarChart3,
        category: "Finance",
        isNew: true,
        gradient: "from-green-500 to-teal-500",
        businessValue: "Predict cash crunches before they happen. Plan growth confidently with accurate forecasts.",
        businessAreas: ['finance', 'strategy', 'operations'],
    },
    {
        id: "expense-tracker-ai",
        name: "AI Expense Tracker",
        description: "Automatically categorize expenses, track receipts with OCR, flag unusual spending, and generate tax-ready reports. Works with all bank accounts.",
        icon: DollarSign,
        category: "Finance",
        gradient: "from-orange-500 to-red-500",
        businessValue: "Save 15+ hours/month on expense tracking. Never lose a receipt. Be audit-ready year-round.",
        businessAreas: ['finance', 'operations'],
    },
    {
        id: "pricing-optimizer",
        name: "Dynamic Pricing Optimizer",
        description: "Optimize product pricing with AI based on demand, competition, seasonality, and market conditions. Maximize profit margins automatically.",
        icon: TrendingUp,
        category: "Finance",
        gradient: "from-indigo-500 to-purple-500",
        businessValue: "Increase revenue by 15-35% with optimal pricing. Stay competitive automatically.",
        businessAreas: ['finance', 'ecommerce', 'strategy'],
    },

    // E-COMMERCE Power-Ups (4)
    {
        id: "product-description-ai",
        name: "Product Description Generator",
        description: "Create compelling, SEO-optimized product descriptions for e-commerce. Bulk generate for 100s of products. Works with Shopify, WooCommerce, Amazon.",
        icon: ShoppingCart,
        category: "E-commerce",
        isPopular: true,
        gradient: "from-orange-500 to-red-500",
        businessValue: "Increase conversion rates by 30-50%. Save hours writing product descriptions manually.",
        businessAreas: ['ecommerce', 'content', 'marketing'],
    },
    {
        id: "cart-abandonment-recovery",
        name: "Cart Abandonment Recovery",
        description: "Automatically recover abandoned carts with personalized email sequences, SMS, and retargeting ads. Recover 20-40% of lost sales.",
        icon: ShoppingCart,
        category: "E-commerce",
        gradient: "from-red-500 to-pink-500",
        businessValue: "Recover $50k-500k+ in lost revenue per year. Turn abandoned carts into completed purchases.",
        businessAreas: ['ecommerce', 'email', 'marketing'],
    },
    {
        id: "inventory-optimizer",
        name: "Inventory Optimization System",
        description: "Predict demand, optimize stock levels, prevent stockouts and overstocking. Multi-warehouse support and supplier management.",
        icon: BarChart3,
        category: "E-commerce",
        isNew: true,
        gradient: "from-teal-500 to-cyan-500",
        businessValue: "Reduce inventory costs by 25-40%. Never miss a sale due to stockouts. Optimize cash flow.",
        businessAreas: ['ecommerce', 'operations', 'finance'],
    },
    {
        id: "review-management-ecommerce",
        name: "Product Review Manager",
        description: "Collect, manage, and showcase customer reviews. Auto-request reviews post-purchase, handle negative feedback, and boost social proof.",
        icon: Star,
        category: "E-commerce",
        gradient: "from-yellow-500 to-amber-500",
        businessValue: "Increase conversions by 35-65% with social proof. Build trust and credibility automatically.",
        businessAreas: ['ecommerce', 'customer', 'marketing'],
    },

    // CONTENT CREATION Power-Ups (4)
    {
        id: "video-script-writer",
        name: "Video Script Writer",
        description: "Generate engaging video scripts for YouTube, TikTok, Instagram Reels, and video ads. Hook, value, CTA included. Perfect for content creators.",
        icon: Video,
        category: "Content Creation",
        hasTools: true, // Has script editor tool
        gradient: "from-pink-500 to-rose-500",
        businessValue: "Create video content 10x faster. Grow your audience with consistent, engaging videos.",
        businessAreas: ['content', 'social', 'marketing'],
    },
    {
        id: "content-calendar-planner",
        name: "Content Calendar Planner",
        description: "Generate 30-90 day content plans for blog, social media, email, and video. Auto-schedule posts across platforms. Never run out of content ideas.",
        icon: Calendar,
        category: "Content Strategy",
        hasTools: true, // Has calendar tool
        gradient: "from-teal-500 to-cyan-500",
        businessValue: "Stay consistent with content. Plan entire quarters in 30 minutes. Grow 3x faster with consistency.",
        businessAreas: ['content', 'marketing', 'social'],
    },
    {
        id: "blog-post-writer-ai",
        name: "AI Blog Post Writer",
        description: "Write SEO-optimized 2000+ word blog posts in minutes. Research, outline, write, and optimize for keywords. Includes images and meta descriptions.",
        icon: PenTool,
        category: "Content Creation",
        isPopular: true,
        gradient: "from-indigo-500 to-blue-500",
        businessValue: "Publish 5-10x more content. Drive organic traffic without hiring writers. Rank faster on Google.",
        businessAreas: ['content', 'marketing', 'strategy'],
    },
    {
        id: "content-repurposing",
        name: "Content Repurposing Engine",
        description: "Turn one piece of content into 20+. Blog → social posts, video → clips, podcast → articles. Maximize content ROI across all platforms.",
        icon: Sparkles,
        category: "Content Creation",
        isNew: true,
        gradient: "from-purple-500 to-pink-500",
        businessValue: "Get 10x more mileage from every piece of content. Save 20+ hours/week on content creation.",
        businessAreas: ['content', 'social', 'marketing'],
    },

    // EMAIL MARKETING Power-Ups (4)
    {
        id: "email-sequence-automator",
        name: "Email Sequence Automator",
        description: "Build complete email funnels with welcome series, nurture campaigns, cart abandonment, and win-back sequences. Integrates with all major ESPs.",
        icon: Mail,
        category: "Email Marketing",
        isPopular: true,
        gradient: "from-amber-500 to-orange-500",
        businessValue: "Increase email revenue by 40-60%. Automate customer journeys that run 24/7.",
        businessAreas: ['email', 'marketing', 'ecommerce'],
    },
    {
        id: "email-subject-optimizer",
        name: "Subject Line Optimizer",
        description: "Generate and test subject lines that get opened. AI analyzes your audience and generates high-performing subject lines with predicted open rates.",
        icon: Mail,
        category: "Email Marketing",
        gradient: "from-blue-500 to-cyan-500",
        businessValue: "Increase open rates by 25-45%. Never struggle with subject lines again.",
        businessAreas: ['email', 'marketing'],
    },
    {
        id: "email-list-segmentation",
        name: "Smart List Segmentation",
        description: "Automatically segment your email list based on behavior, demographics, and engagement. Send hyper-targeted campaigns that convert.",
        icon: Target,
        category: "Email Marketing",
        isNew: true,
        gradient: "from-purple-500 to-indigo-500",
        businessValue: "Increase email ROI by 3-5x with targeted messaging. Stop sending blanket emails.",
        businessAreas: ['email', 'marketing', 'analytics'],
    },
    {
        id: "newsletter-generator",
        name: "AI Newsletter Generator",
        description: "Create engaging newsletters in minutes. Curate content, write copy, design layout, and schedule delivery. Perfect for thought leaders and businesses.",
        icon: FileText,
        category: "Email Marketing",
        gradient: "from-green-500 to-teal-500",
        businessValue: "Publish consistent newsletters that build authority. Save 5+ hours per newsletter.",
        businessAreas: ['email', 'content', 'marketing'],
    },

    // CUSTOMER SUPPORT Power-Ups (3)
    {
        id: "chatbot-support-ai",
        name: "AI Support Chatbot",
        description: "Deploy intelligent chatbots that handle 80% of customer support. Train on your FAQs, docs, and past conversations. 24/7 availability.",
        icon: MessageSquare,
        category: "Customer Service",
        gradient: "from-blue-500 to-indigo-500",
        businessValue: "Reduce support costs by 60-70%. Answer customers instantly, improve satisfaction scores.",
        businessAreas: ['customer', 'operations', 'ecommerce'],
    },
    {
        id: "ticket-management-ai",
        name: "AI Ticket Management",
        description: "Automatically categorize, prioritize, and route support tickets. AI suggests responses, tracks SLAs, and identifies trending issues.",
        icon: Headphones,
        category: "Customer Service",
        isNew: true,
        gradient: "from-cyan-500 to-blue-500",
        businessValue: "Respond 3x faster. Reduce ticket backlog by 60%. Improve customer satisfaction scores.",
        businessAreas: ['customer', 'operations'],
    },
    {
        id: "knowledge-base-builder",
        name: "AI Knowledge Base Builder",
        description: "Automatically generate FAQs, help articles, and documentation from support tickets and conversations. Self-serve support that deflects 40-60% of tickets.",
        icon: Brain,
        category: "Customer Service",
        gradient: "from-purple-500 to-pink-500",
        businessValue: "Deflect 40-60% of support tickets. Empower customers to help themselves. Scale support efficiently.",
        businessAreas: ['customer', 'content', 'operations'],
    },

    // SOCIAL MEDIA Power-Ups (4)
    {
        id: "social-media-manager",
        name: "Social Media Manager",
        description: "Create, schedule, and publish content across all platforms. AI generates captions, hashtags, and optimal posting times. Analytics included.",
        icon: Share2,
        category: "Social Media",
        isPopular: true,
        gradient: "from-cyan-500 to-blue-500",
        businessValue: "Manage all social media from one place. Save 15+ hours/week and grow followers 3x faster.",
        businessAreas: ['social', 'marketing', 'content'],
    },
    {
        id: "influencer-outreach",
        name: "Influencer Outreach Tool",
        description: "Find relevant influencers in your niche, analyze their audience, generate personalized outreach emails. Track partnerships and ROI.",
        icon: Users,
        category: "Influencer Marketing",
        isNew: true,
        gradient: "from-purple-500 to-pink-500",
        businessValue: "Scale influencer campaigns. Reach 10x more influencers with personalized outreach that converts.",
        businessAreas: ['social', 'marketing', 'strategy'],
    },
    {
        id: "social-listening-tool",
        name: "Social Listening & Monitoring",
        description: "Monitor brand mentions, competitors, and industry trends across all social platforms. Get alerts on opportunities and threats in real-time.",
        icon: Search,
        category: "Social Media",
        gradient: "from-teal-500 to-cyan-500",
        businessValue: "Stay ahead of trends. Respond to customers 10x faster. Protect your brand reputation.",
        businessAreas: ['social', 'customer', 'strategy'],
    },
    {
        id: "ugc-content-sourcing",
        name: "UGC Content Sourcing",
        description: "Find, request, and manage user-generated content. Automate permissions, organize assets, and repurpose UGC across marketing channels.",
        icon: Users,
        category: "Social Media",
        gradient: "from-pink-500 to-rose-500",
        businessValue: "Build authentic social proof. Save thousands on content creation. Increase engagement by 50-80%.",
        businessAreas: ['social', 'marketing', 'ecommerce'],
    },

    // ANALYTICS Power-Ups (3)
    {
        id: "conversion-rate-optimizer",
        name: "Conversion Rate Optimizer",
        description: "Analyze your website, identify conversion leaks, get AI-powered recommendations. Heatmaps, user flow analysis, and CRO experiments.",
        icon: TrendingUp,
        category: "Conversion",
        isPopular: true,
        gradient: "from-green-500 to-emerald-500",
        businessValue: "Turn more visitors into customers. Typical results: 20-60% increase in conversion rate.",
        businessAreas: ['analytics', 'marketing', 'ecommerce'],
    },
    {
        id: "dashboard-builder",
        name: "Custom Dashboard Builder",
        description: "Build custom analytics dashboards that pull data from all your tools. Track KPIs, visualize metrics, and share reports with stakeholders.",
        icon: BarChart3,
        category: "Analytics",
        isNew: true,
        gradient: "from-blue-500 to-purple-500",
        businessValue: "See all your metrics in one place. Make data-driven decisions 10x faster. Save 10+ hours/week.",
        businessAreas: ['analytics', 'operations', 'strategy'],
    },
    {
        id: "predictive-analytics-ai",
        name: "Predictive Analytics Engine",
        description: "Forecast sales, predict churn, identify growth opportunities with AI. Machine learning models trained on your business data.",
        icon: Brain,
        category: "Analytics",
        gradient: "from-indigo-500 to-purple-500",
        businessValue: "See the future of your business. Make proactive decisions. Prevent problems before they happen.",
        businessAreas: ['analytics', 'strategy', 'finance'],
    },

    // OPERATIONS Power-Ups (3)
    {
        id: "workflow-automation",
        name: "Workflow Automation Builder",
        description: "Build custom workflows that connect all your tools. No-code automation builder with 1000+ integrations. Zapier on steroids.",
        icon: Zap,
        category: "Operations",
        isPopular: true,
        gradient: "from-orange-500 to-red-500",
        businessValue: "Automate repetitive tasks. Save 20+ hours/week per team member. Reduce errors by 90%.",
        businessAreas: ['operations', 'tech'],
    },
    {
        id: "sop-documentation",
        name: "SOP Documentation Generator",
        description: "Automatically document processes, create SOPs, and build training materials. Screen recording, step-by-step guides, and video tutorials.",
        icon: FileCode,
        category: "Operations",
        isNew: true,
        gradient: "from-purple-500 to-indigo-500",
        businessValue: "Scale your business with documented processes. Onboard new team members 5x faster.",
        businessAreas: ['operations', 'content'],
    },
    {
        id: "project-management-ai",
        name: "AI Project Manager",
        description: "Automatically create project plans, assign tasks, track progress, and predict delays. Integrates with Asana, Trello, Monday, and more.",
        icon: Calendar,
        category: "Operations",
        gradient: "from-teal-500 to-cyan-500",
        businessValue: "Deliver projects on time, every time. Reduce project delays by 60%. Keep teams aligned effortlessly.",
        businessAreas: ['operations', 'strategy'],
    },

    // TECHNICAL/DEV Power-Ups (3)
    {
        id: "api-integration-wizard",
        name: "API Integration Wizard",
        description: "Connect any API without code. Visual builder for complex integrations, data transformations, and webhooks. Non-technical friendly.",
        icon: FileCode,
        category: "Technical",
        isNew: true,
        gradient: "from-green-500 to-teal-500",
        businessValue: "Build integrations in hours, not weeks. No developers needed. Save $10k-50k per integration.",
        businessAreas: ['tech', 'operations'],
    },
    {
        id: "website-speed-optimizer",
        name: "Website Speed Optimizer",
        description: "Automatically optimize images, compress code, implement caching, and fix performance issues. Monitor Core Web Vitals in real-time.",
        icon: Zap,
        category: "Technical",
        gradient: "from-blue-500 to-cyan-500",
        businessValue: "Load your site 3x faster. Improve SEO rankings. Increase conversions by 20-40% with faster pages.",
        businessAreas: ['tech', 'marketing', 'ecommerce'],
    },
    {
        id: "ab-testing-platform",
        name: "A/B Testing Platform",
        description: "Test headlines, layouts, CTAs, and more without code. Statistical significance calculator, winner detection, and automatic traffic splitting.",
        icon: GitCompare,
        category: "Technical",
        gradient: "from-purple-500 to-pink-500",
        businessValue: "Optimize everything with data. Increase conversions by 30-50% through continuous testing.",
        businessAreas: ['tech', 'marketing', 'analytics'],
    },

    // STRATEGY Power-Ups (3)
    {
        id: "competitor-intelligence",
        name: "Competitor Intelligence",
        description: "Track competitor ads, social media, content strategy, pricing, and SEO. Get alerts on new campaigns. Stay ahead of the market.",
        icon: GitCompare,
        category: "Market Research",
        gradient: "from-indigo-500 to-purple-500",
        businessValue: "Know exactly what works in your industry. Make data-driven decisions to beat competitors.",
        businessAreas: ['strategy', 'marketing', 'analytics'],
    },
    {
        id: "market-research-ai",
        name: "AI Market Research Tool",
        description: "Conduct market research, analyze trends, identify opportunities, and validate ideas with AI. Survey creation, data analysis, and insights generation.",
        icon: Search,
        category: "Market Research",
        isNew: true,
        gradient: "from-blue-500 to-indigo-500",
        businessValue: "Make informed decisions. Validate ideas before investing. Identify opportunities competitors miss.",
        businessAreas: ['strategy', 'marketing'],
    },
    {
        id: "business-plan-generator",
        name: "Business Plan Generator",
        description: "Create professional business plans, financial projections, and pitch decks with AI. Investor-ready documents in hours, not weeks.",
        icon: Lightbulb,
        category: "Strategy",
        gradient: "from-purple-500 to-pink-500",
        businessValue: "Raise capital faster. Create plans that impress investors. Save $5k-15k on consultants.",
        businessAreas: ['strategy', 'finance'],
    },

    // DESIGN/CREATIVE Power-Ups (3)
    {
        id: "brand-voice-trainer",
        name: "Brand Voice Trainer",
        description: "Train AI to write in your exact brand voice. Analyzes your best content, maintains consistency across all marketing materials.",
        icon: Brain,
        category: "Branding",
        gradient: "from-fuchsia-500 to-purple-500",
        businessValue: "Maintain brand consistency at scale. Sound authentic across all channels without micro-managing.",
        businessAreas: ['content', 'marketing'],
    },
    {
        id: "logo-design-ai",
        name: "AI Logo & Brand Designer",
        description: "Generate professional logos, color palettes, typography, and brand guidelines with AI. Get complete brand identity in minutes.",
        icon: Palette,
        category: "Design",
        isNew: true,
        gradient: "from-pink-500 to-rose-500",
        businessValue: "Launch your brand for $99 instead of $5k. Get professional designs instantly.",
        businessAreas: ['marketing', 'strategy'],
    },
    {
        id: "graphic-template-generator",
        name: "Graphic Template Generator",
        description: "Create custom templates for social posts, ads, presentations, and more. Brand-consistent designs with one click.",
        icon: Sparkles,
        category: "Design",
        gradient: "from-orange-500 to-red-500",
        businessValue: "Design 10x faster. Maintain brand consistency. No designer needed for daily graphics.",
        businessAreas: ['marketing', 'social', 'content'],
    },

    // REPUTATION MANAGEMENT Power-Ups (1)
    {
        id: "review-response-ai",
        name: "Review Response Generator",
        description: "Auto-respond to customer reviews across Google, Yelp, Amazon, Trustpilot. Maintain brand voice, handle negative reviews professionally.",
        icon: Star,
        category: "Reputation Management",
        gradient: "from-yellow-500 to-amber-500",
        businessValue: "Save 10+ hours/week. Improve star ratings by 0.5-1.0 with consistent, professional responses.",
        businessAreas: ['customer', 'marketing', 'ecommerce'],
    },
];
