import { 
    Sparkles, 
    Zap, 
    Target, 
    TrendingUp, 
    Mail, 
    MessageSquare, 
    Image as ImageIcon, 
    FileText,
    BarChart3,
    Globe,
    Share2,
    Brain,
    Search,
    ShoppingCart,
    Video,
    Users,
    Star,
    Calendar,
    Megaphone,
    GitCompare,
    type LucideIcon
} from "lucide-react";

export type PowerUp = {
    id: string;
    name: string;
    description: string;
    icon: LucideIcon;
    category: string;
    isPopular?: boolean;
    isNew?: boolean;
    gradient: string;
    businessValue: string; // What problem it solves
};

export const POWER_UPS: PowerUp[] = [
    {
        id: "ai-ad-creator",
        name: "AI Static Ad Creator",
        description: "Generate high-converting static ads using advanced AI image models (Flux, Stable Diffusion, Midjourney-style). Perfect for Facebook, Instagram, LinkedIn, and display ads.",
        icon: ImageIcon,
        category: "Advertising",
        isNew: true,
        isPopular: true,
        gradient: "from-violet-500 to-purple-500",
        businessValue: "Create professional ads in minutes instead of hiring designers. Save $500-2000 per campaign.",
    },
    {
        id: "seo-geo-optimizer",
        name: "SEO/GEO Optimizer Pro",
        description: "Complete SEO analysis with keyword research, meta tag generation, schema markup, local SEO, and GEO-targeted content optimization. Rank higher on Google.",
        icon: Search,
        category: "SEO & Growth",
        isPopular: true,
        gradient: "from-emerald-500 to-green-500",
        businessValue: "Increase organic traffic by 200-500%. Get found by customers searching for your products/services.",
    },
    {
        id: "product-description-ai",
        name: "Product Description Generator",
        description: "Create compelling, SEO-optimized product descriptions for e-commerce. Bulk generate for 100s of products. Works with Shopify, WooCommerce, Amazon.",
        icon: ShoppingCart,
        category: "E-commerce",
        isPopular: true,
        gradient: "from-orange-500 to-red-500",
        businessValue: "Increase conversion rates by 30-50%. Save hours writing product descriptions manually.",
    },
    {
        id: "landing-page-builder",
        name: "AI Landing Page Builder",
        description: "Build high-converting landing pages with AI. Automatic A/B testing, CRO recommendations, and mobile optimization. Deploy in minutes.",
        icon: FileText,
        category: "Conversion",
        isNew: true,
        gradient: "from-blue-500 to-cyan-500",
        businessValue: "Launch campaigns faster. Improve conversion rates by 25-40% with AI-optimized designs.",
    },
    {
        id: "video-script-writer",
        name: "Video Script Writer",
        description: "Generate engaging video scripts for YouTube, TikTok, Instagram Reels, and video ads. Hook, value, CTA included. Perfect for content creators.",
        icon: Video,
        category: "Content Creation",
        gradient: "from-pink-500 to-rose-500",
        businessValue: "Create video content 10x faster. Grow your audience with consistent, engaging videos.",
    },
    {
        id: "email-sequence-automator",
        name: "Email Sequence Automator",
        description: "Build complete email funnels with welcome series, nurture campaigns, cart abandonment, and win-back sequences. Integrates with all major ESPs.",
        icon: Mail,
        category: "Email Marketing",
        isPopular: true,
        gradient: "from-amber-500 to-orange-500",
        businessValue: "Increase email revenue by 40-60%. Automate customer journeys that run 24/7.",
    },
    {
        id: "competitor-intelligence",
        name: "Competitor Intelligence",
        description: "Track competitor ads, social media, content strategy, pricing, and SEO. Get alerts on new campaigns. Stay ahead of the market.",
        icon: GitCompare,
        category: "Market Research",
        gradient: "from-indigo-500 to-purple-500",
        businessValue: "Know exactly what works in your industry. Make data-driven decisions to beat competitors.",
    },
    {
        id: "review-response-ai",
        name: "Review Response Generator",
        description: "Auto-respond to customer reviews across Google, Yelp, Amazon, Trustpilot. Maintain brand voice, handle negative reviews professionally.",
        icon: Star,
        category: "Reputation Management",
        gradient: "from-yellow-500 to-amber-500",
        businessValue: "Save 10+ hours/week. Improve star ratings by 0.5-1.0 with consistent, professional responses.",
    },
    {
        id: "content-calendar-planner",
        name: "Content Calendar Planner",
        description: "Generate 30-90 day content plans for blog, social media, email, and video. Auto-schedule posts across platforms. Never run out of content ideas.",
        icon: Calendar,
        category: "Content Strategy",
        gradient: "from-teal-500 to-cyan-500",
        businessValue: "Stay consistent with content. Plan entire quarters in 30 minutes. Grow 3x faster with consistency.",
    },
    {
        id: "conversion-rate-optimizer",
        name: "Conversion Rate Optimizer",
        description: "Analyze your website, identify conversion leaks, get AI-powered recommendations. Heatmaps, user flow analysis, and CRO experiments.",
        icon: TrendingUp,
        category: "Conversion",
        isPopular: true,
        gradient: "from-green-500 to-emerald-500",
        businessValue: "Turn more visitors into customers. Typical results: 20-60% increase in conversion rate.",
    },
    {
        id: "influencer-outreach",
        name: "Influencer Outreach Tool",
        description: "Find relevant influencers in your niche, analyze their audience, generate personalized outreach emails. Track partnerships and ROI.",
        icon: Users,
        category: "Influencer Marketing",
        isNew: true,
        gradient: "from-purple-500 to-pink-500",
        businessValue: "Scale influencer campaigns. Reach 10x more influencers with personalized outreach that converts.",
    },
    {
        id: "sales-funnel-builder",
        name: "Sales Funnel Builder",
        description: "Build complete sales funnels with order bumps, upsells, downsells, and thank you pages. Maximize revenue per customer.",
        icon: Zap,
        category: "Sales",
        gradient: "from-red-500 to-orange-500",
        businessValue: "Increase average order value by 30-80%. Turn $50 customers into $150+ customers.",
    },
    {
        id: "chatbot-support-ai",
        name: "AI Support Chatbot",
        description: "Deploy intelligent chatbots that handle 80% of customer support. Train on your FAQs, docs, and past conversations. 24/7 availability.",
        icon: MessageSquare,
        category: "Customer Service",
        gradient: "from-blue-500 to-indigo-500",
        businessValue: "Reduce support costs by 60-70%. Answer customers instantly, improve satisfaction scores.",
    },
    {
        id: "social-media-manager",
        name: "Social Media Manager",
        description: "Create, schedule, and publish content across all platforms. AI generates captions, hashtags, and optimal posting times. Analytics included.",
        icon: Share2,
        category: "Social Media",
        isPopular: true,
        gradient: "from-cyan-500 to-blue-500",
        businessValue: "Manage all social media from one place. Save 15+ hours/week and grow followers 3x faster.",
    },
    {
        id: "brand-voice-trainer",
        name: "Brand Voice Trainer",
        description: "Train AI to write in your exact brand voice. Analyzes your best content, maintains consistency across all marketing materials.",
        icon: Brain,
        category: "Branding",
        gradient: "from-fuchsia-500 to-purple-500",
        businessValue: "Maintain brand consistency at scale. Sound authentic across all channels without micro-managing.",
    },
    {
        id: "ad-campaign-optimizer",
        name: "Ad Campaign Optimizer",
        description: "Optimize Facebook, Google, TikTok, and LinkedIn ads with AI. Automatic bid adjustments, audience refinement, and creative testing.",
        icon: Target,
        category: "Advertising",
        gradient: "from-rose-500 to-red-500",
        businessValue: "Reduce ad costs by 30-50%. Increase ROAS by 2-5x with AI-powered optimization.",
    },
];

